### ISSUE TITLE
Blaze Guardians spawn when spawn weight set to 0 and "allow_guardian_spawner_spawn": false

### ISSUE THREAD

**Issue by ShinyRobotGod** [Globox1997/AdventureZ#126]
Hello.

A single blaze guardian spawns when I first activate a blaze spawner.  In the config, blaze guardian spawn weight is set to zero and "allow_guardian_spawner_spawn": false.  This occurs over multiple worlds and with multiple minecraft restarts.  

I tested by telelporting around a new nether.  A single blaze guardian spawned each time I activated the blaze spawner for the first time.  I did not notice any more blaze guardian spawns after that, but did not hang out at each blaze spawner for more than half a dozen spawn cycles.  Reapproaching a spawner already triggered at least once did not result in a new blaze guardian spawning.

I wonder if "allow_guardian_spawner_spawn": false is the right command.  It doesn't use the word "blaze" and there are ocean guardians.  I noticed when I used the kill command that two AdventureZ types appeared in the list: "blaze_guardian" and "blaze_guardian_shield".

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/AdventureZ/commit/b6e900c7760c4258d7ec34a3c77cbaac10ccc299](https://github.com/Globox1997/AdventureZ/commit/b6e900c7760c4258d7ec34a3c77cbaac10ccc299) and [https://github.com/Globox1997/AdventureZ/commit/612c188176868195de26fae541207a295e5d1a13](https://github.com/Globox1997/AdventureZ/commit/612c188176868195de26fae541207a295e5d1a13)
