### ISSUE TITLE
Canvas texture failing issue

### ISSUE THREAD

**Issue by GeradesoLukas** [Globox1997/AdventureZ#20]
So this only happens to the mobs that have an overlay, which are:
- The Blackstone Golem (Both stages)
- Soul Reaper
- Summoner
- Nightmare

I think that canvas does not know that the texture is transparent and that's why it isn't working. Maybe that's a help ^^"

![2021-02-27_18 48 24](https://user-images.githubusercontent.com/59490449/109395534-2d928b80-792d-11eb-9f9d-757bd1ede10d.png)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/AdventureZ/commit/6fa2d165b65c6ebb29144fe636077c08dca1e108](https://github.com/Globox1997/AdventureZ/commit/6fa2d165b65c6ebb29144fe636077c08dca1e108) commit and added bloom with [https://github.com/Globox1997/AdventureZ/commit/72627b1946e48771d63ca6d3d0b0994d93fe4be4](https://github.com/Globox1997/AdventureZ/commit/72627b1946e48771d63ca6d3d0b0994d93fe4be4)
