### ISSUE TITLE
Description Suggestion

### ISSUE THREAD

**Issue by Aspyro** [Globox1997/AdventureZ#4]
Hi ! 
I'm curious about this mod. But except a brief description on Curseforge, I don't see anywhere a list of features.
Would you mind my help building one ?

> **What is the main goal of the mod ?**

From what I saw, the main topic is to add Vanilla-like mobs. Could we get more details on those mobs ?
What are there names, where can we find them (Dimension + biome + y-level ?) ? What kind of damage do they deal ? Do they spawn in group or alone ? Passive, aggressive at sight or defensive ( = agressive if you hit them).

> **There are mobs but there are bosses too !**

Then, same questions as before. Plus : are there invocations ? Can you describe them ? Do they have a lot of Health Points or resistance ?

> **There is a new armor set !**

Tell me more ? How can we get it ?
You said there is a special effect ? Which one ?

> **The mod is still in development**

I'm happy to read it ! It means there will be some more (or plenty of) things added in the next updates !
Maybe use this issue to develop your ideas before writing it in the mod description ?

> **More things to think of ?**

Sure. I personally don't know how to do it, but maybe it would be great to get a config file to activate/desactivate one or more mobs, or even personalize their attributes ?

All I did here was to read the Curseforge page and ask related questions (answered or not) to get a better idea of your interesting mod. I also permitted myself to add a suggestion in this.
It will then be easier for everyone to add this mod in modpacks (i guess). It is my goal, so I hope it will be helpful for others !

Thanks for reading and reacting to this 😄

**Comment by Globox1997** [comment]
Hey Aspryro :)
Since I´m most of the time to lazy to update my mod pages, would be awesome if you would build one and publish it anywhere :D If you want to publish it at a separate website I would add a link, otherwise I would just give you permission to add it :) 
Yes the main goal is to add new mobs, where I have at least still 5 on my to do list, progression is very slow.
Necromancer: 45HP, No direct damage, summons wither puppets + rarely wither skeletons, spawns in the nether mainly in nether fortresses, spawns alone, always aggressive, drops: gold nuggets and enchanted book lvl30
Wither Puppet: 14HP, 5Dmg, If owner dies, it dies too, summed by necromancer, always aggressive, no drops
Nightmare: 40HP, Passive, spawns with Soul Reaper in nether in soulsand valleys, no drops
Soul Reaper: Dmg unknown, Attacks close with sword, far with bow (shoots withered + piercing arrows), spawns with nightmare, always aggressive, drops coal, bone and witherskeleton head
Stone Golem: Summonable Boss needs 4 gilded stone + stone holder in circle with radius 5 blocks and platform out of blackstone (or other blackstone block variants), 600HP, 12Dmg, throws blackstone, second phase which makes it stronger and faster, always aggressive, drops blackstone + debris,scrap, gilded netherite fragment, stone golem heart, after death splits in two small stone golems
Small Stone Golem: 50HP, 6Dmg, spawns in nether in basalt biomes, always aggressive, drops blackstone, debris, scrap
- Different drop chances
Gilded Netherite Armor: It's basically an upgraded netherite armor
Upgrade the netherite armor with the gilded netherite shards (get them from the blackstone golem) at the smithing table
Full set enables fire resistance buff, activated with default key "v" which grants 30s of fireresistance, reload 1min (nice burning effect + no fire overlay)
I thought about a config but I´ll wait until I think I have a good amount of mobs otherwise it will just take more time to create new mobs
Next mob will probably be a mesa golem, not sure yet. other ideas are a rideable dragon, rideable gryphon, a mage, drowned pirate, kind of shark, a wale, kind of octopus :)

**Comment by Globox1997** [comment]
For further questions, reopen this issue or write me on discord Globox_Z #1024
