### ISSUE TITLE
Too many Reapers and Nightmares in the Nether and Canvas's rendering problem

### ISSUE THREAD

**Issue by j2151918** [Globox1997/AdventureZ#45]
![2021-07-06_02 36 24](https://user-images.githubusercontent.com/52987021/124581109-61556300-de83-11eb-9281-5d5d9a7b9625.png)
Version 1.2.7
Reapers and Nightmares spawn too often.

**Comment by Globox1997** [comment]
Canvas compat fixed with [https://github.com/Globox1997/AdventureZ/commit/0b7023c95fbe15b73a67bfb091d132521fe142e9](https://github.com/Globox1997/AdventureZ/commit/0b7023c95fbe15b73a67bfb091d132521fe142e9) and fixed spawn with [https://github.com/Globox1997/AdventureZ/commit/10bfe8c653a766f951f6ff0c60b245ab36f7138b#diff-a08336c2776280b4e46de898f27229b8fdd364eeffeb5041d7b6bca352938526](https://github.com/Globox1997/AdventureZ/commit/10bfe8c653a766f951f6ff0c60b245ab36f7138b#diff-a08336c2776280b4e46de898f27229b8fdd364eeffeb5041d7b6bca352938526)
